app:
  server:
    eureka:
      origin: 'http://localhost:8761'
    keycloak:
      origin: 'http://localhost:8181'
  client:
    store-front:
      origin: 'http://localhost:5173'
eureka:
  client:
    serviceUrl:
      defaultZone: '${app.server.eureka.origin}/eureka'

server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #product-service-route
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/** , /v3/api-docs/product-service
        #order-service-route
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/** , /v3/api-docs/order-service
        #inventory-service-route
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventories/** , /v3/api-docs/inventory-service
        #discovery-service-route
        - id: discovery-service
          uri: '${app.server.eureka.origin}'
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
            #- RewritePath=/eureka/web/(?<remaining>.*), /$\{remaining}
        - id: discovery-service-static-resource
          uri: '${app.server.eureka.origin}'
          predicates:
            - Path=/eureka/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins:
              - ${app.client.store-front.origin}
            allowed-methods: '*'
            allowed-headers: '*'
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8181/realms/spring-react-realm'

springdoc:
  api-docs:
    groups:
      enabled: false

  swagger-ui:
    with-credentials: true
    operations-sorter: method

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
          gateway.route.RouteDefinitionLocator: INFO
    root: INFO