server:
  port: 8080

#management.zipkin.tracing.endpoint=http://zipkin:9411
app:
  server:
    eureka:
      origin: 'http://discovery-server:8761'

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://keycloak:8181/realms/spring-react-realm'
