version: "3.0"
services:
  store:
    build: .
    container_name: react-store
    ports:
      - '5173:5173'
      - '4173:4173'
    volumes:
      - .:/app
      - ./app/node_modules
    stdin_open: true
    tty: true